"""
Django settings for app_tracking_system project.

Generated by 'django-admin startproject' using Django 3.2.18.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-y07)qvpv2fe!9()zwkcyv6j!3xu0_r8*$g33!k9n&xn#6cc88x'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'drf_yasg',
    'corsheaders',
    "application",

]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'app_tracking_system.urls'
CORS_ALLOW_ALL_ORIGINS = True

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'app_tracking_system.wsgi.application'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',  # Default permission for all views
    ),
}
# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": "app_tracking_system",
        "USER": "root",
        "PASSWORD": "Vrdella!6",
        "HOST": "localhost",
        "PORT": "3306",
        'OPTIONS': {},
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'USER_ID_FIELD': 'user_id',

}

SWAGGER_SETTINGS = {

    'SECURITY_DEFINITIONS': {


        'Token': {

            'type': 'apiKey',

            'name': 'Authorization',

            'in': 'header'

        }

    },

    'USE_SESSION_AUTH': False,

    'DEFAULT_FIELD_INSPECTORS': [

        'drf_yasg.inspectors.CamelCaseJSONFilter',

        'drf_yasg.inspectors.InlineSerializerInspector',

        'drf_yasg.inspectors.RelatedFieldInspector',

        'drf_yasg.inspectors.ChoiceFieldInspector',

        'drf_yasg.inspectors.FileFieldInspector',

        'drf_yasg.inspectors.DictFieldInspector',

        'drf_yasg.inspectors.SimpleFieldInspector',

        'drf_yasg.inspectors.StringDefaultFieldInspector',

    ],

}
AUTH_USER_MODEL = "application.Users"

MEDIA_ROOT = "C:/project_files/test_060125_frontend/my-react-app/public/uploads"
MEDIA_URL = '/media/'


# {
#   "refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTczNjcwMjAyOSwiaWF0IjoxNzM2NjE1NjI5LCJqdGkiOiI1MTliYjI3MjA2ZTQ0M2MzODY0ODQ4NDRjNGE3YjRhOCIsInVzZXJfaWQiOiJVU1JfOUJTTjQifQ.obTFK00wucdNk7FfP12yabxUeZbgUL_1s814WWqq8iM",
#   "access": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM2NjE2NTI5LCJpYXQiOjE3MzY2MTU2MjksImp0aSI6IjYxODVkNDJhMjBmZTQwZDM4MGU3ZjI2Mzc5Y2QzMTcxIiwidXNlcl9pZCI6IlVTUl85QlNONCJ9.ct1HEnoohVEwMrynDKAZPkwZYl3d0jVRCYNqZO8-2VE"
# }